/* DDL for Main Database **/
CREATE TABLE ORGANIZACAO
( ORG_ID number(10) NOT NULL,
  ORG_NAME varchar2(100) NOT NULL,
  CONSTRAINT ORGANIZACAO_PK PRIMARY KEY (ORG_ID)
);

CREATE TABLE USUARIO
( USR_ID NUMBER(10), 
	USR_NAME VARCHAR2(100),
  USR_USER VARCHAR2(10),
  USR_PASS VARCHAR2(10),
  USR_ORG_ID NUMBER(10),
  CONSTRAINT USUARIO_PK PRIMARY KEY (USR_ID),
  CONSTRAINT FK_ORGANIZACAO
    FOREIGN KEY (USR_ORG_ID)
    REFERENCES ORGANIZACAO(ORG_ID)
);

CREATE TABLE ORG_TENANT
( TEN_ORG_ID NUMBER(10), 
	TEN_TENANT_DS VARCHAR2(100),  
  CONSTRAINT ORG_TENANT_PK PRIMARY KEY (TEN_ORG_ID,TEN_TENANT_DS),
  CONSTRAINT FK_ORG_TENANT_ORG
    FOREIGN KEY (TEN_ORG_ID)
    REFERENCES ORGANIZACAO(ORG_ID)
);

/* Sample data for Main Database */
INSERT INTO ORGANIZACAO (ORG_ID, ORG_NAME) VALUES (1, 'ORG CLIENT 1');
INSERT INTO ORGANIZACAO (ORG_ID, ORG_NAME) VALUES (10001, 'ORG CLIENT 2');
INSERT INTO ORGANIZACAO (ORG_ID, ORG_NAME) VALUES (22, 'ORG CLIENT 3');

INSERT INTO USUARIO (USR_ID, USR_NAME, USR_USER, USR_PASS, USR_ORG_ID) VALUES (1, 'User 1', 'usr01', '12345', 10001);
INSERT INTO USUARIO (USR_ID, USR_NAME, USR_USER, USR_PASS, USR_ORG_ID) VALUES (2, 'User 2', 'usr02', '12345', 1);
INSERT INTO USUARIO (USR_ID, USR_NAME, USR_USER, USR_PASS, USR_ORG_ID) VALUES (3, 'User 3', 'usr03', '12345', 10001);
INSERT INTO USUARIO (USR_ID, USR_NAME, USR_USER, USR_PASS, USR_ORG_ID) VALUES (4, 'User 4', 'usr04', '12345', 22);
INSERT INTO USUARIO (USR_ID, USR_NAME, USR_USER, USR_PASS, USR_ORG_ID) VALUES (5, 'User 5', 'usr05', '12345', 22);

INSERT INTO ORG_TENANT (TEN_ORG_ID, TEN_TENANT_DS) VALUES (1, 'TENANT1');
INSERT INTO ORG_TENANT (TEN_ORG_ID, TEN_TENANT_DS) VALUES (10001, 'TENANT1');
INSERT INTO ORG_TENANT (TEN_ORG_ID, TEN_TENANT_DS) VALUES (22, 'TENANT2');

/** DDL for example tenants (Replicate this for each tenant database/schema) **/
CREATE TABLE "TENANCY1"."COR_MODELO_DOF" 
( MDOF_CODIGO VARCHAR2(2 BYTE), 
  TITULO VARCHAR2(80 BYTE)
);

/** Sample data for example tenants ((Replicate this for each tenant database/schema)) **/
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (AX, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (PL, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (XD, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (26, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (04, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (1B, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (8B, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (17, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (20, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (23, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (24, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (25, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (27, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (28, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (29, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (LH, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (03, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (2D, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (55, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (02, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (01, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (09, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (07, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (08, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (10, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (11, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (21, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (22, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (06, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (99, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (98, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (00, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (77, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (71, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (18, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (13, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (14, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (15, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (16, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (2E, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (97, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (57, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (65, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (59, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (60, TENANCY 1);
INSERT INTO COR_MODELO_DOF (MDOF_CODIGO, TITULO) VALUES (58, TENANCY 1);